### ISSUE TITLE
Extensions as First-Class Fields

### ISSUE THREAD

**Issue by niquola** [rbrush/sql-on-fhir#11]
We need clarification what is `First-Class Fields`

In spec:
```yaml
resourceType: Patient
gender: ...
extension:
 - url: ...race
    valueCoding: 
        code:...
        system: ...

# this is in example
resourceType: Patient
gender: ...
race:
 extension: ...
   value:
      Coding: 
         extension: ....
         code: <code>
         system: <sys>

# this is how i see FCE

resourceType: Patient
gender: ...
race: 
   code: <code>
   system: <sys>


```
